Traceback (most recent call last):
  File "/Users/patrickkavanagh/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/patrickkavanagh/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/patrickkavanagh/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/patrickkavanagh/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/patrickkavanagh/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/patrickkavanagh/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/Users/patrickkavanagh/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/patrickkavanagh/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# user specified
my_input_file = 'det_image_seq1_MIRIMAGE_F1130Wexp1_firstframestep.fits'

# run the step
dm = linearity_step.LinearityStep.call(my_input_file, output_use_model=True, save_results=True)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-3-ab428d818612>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0;31m# run the step[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0mdm[0m [0;34m=[0m [0mlinearity_step[0m[0;34m.[0m[0mLinearityStep[0m[0;34m.[0m[0mcall[0m[0;34m([0m[0mmy_input_file[0m[0;34m,[0m [0moutput_use_model[0m[0;34m=[0m[0;32mTrue[0m[0;34m,[0m [0msave_results[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/jwst/stpipe/step.py[0m in [0;36mcall[0;34m(cls, *args, **kwargs)[0m
[1;32m    534[0m         [0;32mif[0m [0mlen[0m[0;34m([0m[0margs[0m[0;34m)[0m [0;34m>[0m [0;36m0[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    535[0m             [0mfilename[0m [0;34m=[0m [0margs[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 536[0;31m             [0mcrds_config[0m [0;34m=[0m [0mcls[0m[0;34m.[0m[0mget_config_from_reference[0m[0;34m([0m[0mfilename[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    537[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    538[0m             [0mlog_cls[0m[0;34m.[0m[0minfo[0m[0;34m([0m[0;34m"No filename given, cannot retrieve config from CRDS"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/jwst/stpipe/step.py[0m in [0;36mget_config_from_reference[0;34m(cls, dataset, observatory, disable)[0m
[1;32m    733[0m         [0mexceptions[0m [0;34m=[0m [0mcrds_client[0m[0;34m.[0m[0mget_exceptions_module[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    734[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 735[0;31m             ref_file = crds_client.get_reference_file(dataset,
[0m[1;32m    736[0m                                                       [0mpars_model[0m[0;34m.[0m[0mmeta[0m[0;34m.[0m[0mreftype[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    737[0m                                                       [0mobservatory[0m[0;34m=[0m[0mobservatory[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/jwst/stpipe/crds_client.py[0m in [0;36mget_reference_file[0;34m(dataset, reference_file_type, observatory, asn_exptypes)[0m
[1;32m    183[0m     [0;32mif[0m [0misinstance[0m[0;34m([0m[0mdataset[0m[0;34m,[0m [0mstr[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    184[0m         [0;32mfrom[0m [0mjwst[0m [0;32mimport[0m [0mdatamodels[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 185[0;31m         [0;32mwith[0m [0mdatamodels[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mdataset[0m[0;34m,[0m [0masn_exptypes[0m[0;34m=[0m[0masn_exptypes[0m[0;34m)[0m [0;32mas[0m [0mmodel[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    186[0m             return get_multiple_reference_paths(
[1;32m    187[0m                 model, [reference_file_type], observatory)[reference_file_type]

[0;32m~/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/jwst/datamodels/util.py[0m in [0;36mopen[0;34m(init, memmap, **kwargs)[0m
[1;32m    101[0m                 [0mhdulist[0m [0;34m=[0m [0mfits[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0ms3_utils[0m[0;34m.[0m[0mget_object[0m[0;34m([0m[0minit[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    102[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 103[0;31m                 [0mhdulist[0m [0;34m=[0m [0mfits[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0minit[0m[0;34m,[0m [0mmemmap[0m[0;34m=[0m[0mmemmap[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    104[0m             [0mfile_to_close[0m [0;34m=[0m [0mhdulist[0m[0;34m[0m[0;34m[0m[0m
[1;32m    105[0m [0;34m[0m[0m

[0;32m~/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py[0m in [0;36mfitsopen[0;34m(name, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)[0m
[1;32m    162[0m         [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34mf'Empty filename: {name!r}'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    163[0m [0;34m[0m[0m
[0;32m--> 164[0;31m     return HDUList.fromfile(name, mode, memmap, save_backup, cache,
[0m[1;32m    165[0m                             lazy_load_hdus, **kwargs)
[1;32m    166[0m [0;34m[0m[0m

[0;32m~/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py[0m in [0;36mfromfile[0;34m(cls, fileobj, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)[0m
[1;32m    401[0m         """
[1;32m    402[0m [0;34m[0m[0m
[0;32m--> 403[0;31m         return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
[0m[1;32m    404[0m                              [0msave_backup[0m[0;34m=[0m[0msave_backup[0m[0;34m,[0m [0mcache[0m[0;34m=[0m[0mcache[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    405[0m                              lazy_load_hdus=lazy_load_hdus, **kwargs)

[0;32m~/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py[0m in [0;36m_readfrom[0;34m(cls, fileobj, data, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)[0m
[1;32m   1052[0m             [0;32mif[0m [0;32mnot[0m [0misinstance[0m[0;34m([0m[0mfileobj[0m[0;34m,[0m [0m_File[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1053[0m                 [0;31m# instantiate a FITS file object (ffo)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1054[0;31m                 [0mfileobj[0m [0;34m=[0m [0m_File[0m[0;34m([0m[0mfileobj[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0mmode[0m[0;34m,[0m [0mmemmap[0m[0;34m=[0m[0mmemmap[0m[0;34m,[0m [0mcache[0m[0;34m=[0m[0mcache[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1055[0m             [0;31m# The Astropy mode is determined by the _File initializer if the[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1056[0m             [0;31m# supplied mode was None[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/astropy/utils/decorators.py[0m in [0;36mwrapper[0;34m(*args, **kwargs)[0m
[1;32m    533[0m                     [0mwarnings[0m[0;34m.[0m[0mwarn[0m[0;34m([0m[0mmessage[0m[0;34m,[0m [0mwarning_type[0m[0;34m,[0m [0mstacklevel[0m[0;34m=[0m[0;36m2[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    534[0m [0;34m[0m[0m
[0;32m--> 535[0;31m             [0;32mreturn[0m [0mfunction[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    536[0m [0;34m[0m[0m
[1;32m    537[0m         [0;32mreturn[0m [0mwrapper[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/astropy/io/fits/file.py[0m in [0;36m__init__[0;34m(self, fileobj, mode, memmap, overwrite, cache)[0m
[1;32m    191[0m             [0mself[0m[0;34m.[0m[0m_open_fileobj[0m[0;34m([0m[0mfileobj[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0moverwrite[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    192[0m         [0;32melif[0m [0misinstance[0m[0;34m([0m[0mfileobj[0m[0;34m,[0m [0mstr[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 193[0;31m             [0mself[0m[0;34m.[0m[0m_open_filename[0m[0;34m([0m[0mfileobj[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0moverwrite[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    194[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    195[0m             [0mself[0m[0;34m.[0m[0m_open_filelike[0m[0;34m([0m[0mfileobj[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0moverwrite[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/astropy/io/fits/file.py[0m in [0;36m_open_filename[0;34m(self, filename, mode, overwrite)[0m
[1;32m    572[0m [0;34m[0m[0m
[1;32m    573[0m         [0;32mif[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0m_try_read_compressed[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mname[0m[0;34m,[0m [0mmagic[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0mext[0m[0;34m=[0m[0mext[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 574[0;31m             [0mself[0m[0;34m.[0m[0m_file[0m [0;34m=[0m [0mfileobj_open[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mname[0m[0;34m,[0m [0mIO_FITS_MODES[0m[0;34m[[0m[0mmode[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    575[0m             [0mself[0m[0;34m.[0m[0mclose_on_error[0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m
[1;32m    576[0m [0;34m[0m[0m

[0;32m~/anaconda3/anaconda3/envs/jwst7.6/lib/python3.8/site-packages/astropy/io/fits/util.py[0m in [0;36mfileobj_open[0;34m(filename, mode)[0m
[1;32m    394[0m     """
[1;32m    395[0m [0;34m[0m[0m
[0;32m--> 396[0;31m     [0;32mreturn[0m [0mopen[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0mbuffering[0m[0;34m=[0m[0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    397[0m [0;34m[0m[0m
[1;32m    398[0m [0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'det_image_seq1_MIRIMAGE_F1130Wexp1_firstframestep.fits'
FileNotFoundError: [Errno 2] No such file or directory: 'det_image_seq1_MIRIMAGE_F1130Wexp1_firstframestep.fits'

